services:
  - type: web
    name: laravel-app
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      # Agrega aquí tus variables de entorno reales o usa el panel de Render
